#!/usr/bin/env sh

# Starts a Zombienet network with the provided config file, and saves its pid in a file under the `tmp` directory in the root of the project.

if [ $# -ne 1 ]; then
    echo 'One argument indicating the Zombienet config file path is expected.'
    exit 1
fi

# Path of the Zombienet config file provided to the script
CONFIG_FILE_PATH=$1
# Tmp folder under "./tmp" from the project's root
TMP_FOLDER_FOR_FILE="./tmp/$(dirname $CONFIG_FILE_PATH)"
# Path to store the pid of the current Zombienet setup
TMP_PID_FILE_FOR_FILE="./tmp/$CONFIG_FILE_PATH"
# Path to store the out logs of the current Zombienet setup
TMP_LOG_FILE_FOR_FILE="$TMP_PID_FILE_FOR_FILE-out.txt"
# Path to store the err logs of the current Zombienet setup
TMP_ERR_FILE_FOR_FILE="$TMP_PID_FILE_FOR_FILE-err.txt"

set -x
mkdir -p $TMP_FOLDER_FOR_FILE && touch $TMP_FILE_FOR_FILE $TMP_LOG_FILE_FOR_FILE $TMP_ERR_FILE_FOR_FILE
yarn zombienet --spawn-concurrency 3 spawn $CONFIG_FILE_PATH >$TMP_LOG_FILE_FOR_FILE 2>$TMP_ERR_FILE_FOR_FILE &
echo $! > $TMP_PID_FILE_FOR_FILE
